services:
  api:
    container_name: api-hakuna
    build: ./server
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db
    environment:
      - WDS_SOCKET_PORT=5000
      - WATCHPACK_POLLING= true 
    env_file:
      - ./server/.env
    volumes:
      - ./server:/api
  
  db:
    image: mysql
    ports: 
      - 3306:3306
    env_file:
      - ./server/.env
  client-react:
    container_name: react-hakuna
    build: ./client
    environment:
      - WDS_SOCKET_PORT=3000
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    depends_on: 
      - api 
    volumes: 
      - ./client:/app-react
