services:
  server:
    container_name: api-hakuna
    build: ./server
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db
    environment:
      - WDS_SOCKET_PORT=5000
      - NODE_ENV=production
    env_file:
      - ./server/.env
    volumes:
      - ./server:/api

  db:
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - ./server/.env
    environment:
      MYSQL_DATABASE: 'romeo'
      MYSQL_ROOT_PASSWORD: 'Romeo62-'

  client:
    container_name: react-hakuna
    build: ./client
    environment:
      - WDS_SOCKET_PORT=3000
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      - server
    volumes:
      - ./client:/app-react

  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx

volumes:
  web-client-build: